#!/bin/sh

# Starts/stops the aesdsocket server, launching it in daemon mode
# Supported arguments are:
#

SERVICE_NAME=aesdsocket

case "$1" in
start)
	echo "Starting ${SERVICE_NAME}"
	start-stop-daemon -S -n ${SERVICE_NAME} -a /usr/bin/aesdsocket -d
	;;
stop)
	echo "Stopping ${SERVICE_NAME}"
	start-stop-daemon -K -n ${SERVICE_NAME} --signal TERM
	;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac

exit 1
